[package]
name = "encode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = { version = "0.6", features = ["std"] }
cbc = "0.1.2"
aes = "0.8"
hex = "0.4"